rabbit:
  image: rafakato/rabbitmq-delayed-message-exchange:3.6.1-management
  hostname: rabbit
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
  ports:
    - "5672:5672"
    - "15672:15672"
mongo:
  image: mongo
  hostname: mongo
  ports:
    - "27017:27017"
sqlserver:
  image: microsoft/mssql-server-linux
  hostname: sqlserver
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Teste!@#
  ports:
    - "1433:1433"